#!/bin/bash

case $1 in
  reinstall)
    printf ">>> remove node_modules and lock file then install latest dependencies, ing ......\n"
    rm -rf node_modules package-lock.json && npm i
    printf "\n>>> reinstall success\n"
    ;;
esac
